### ISSUE TITLE
GSSDK 3.4.0 does not support SNI

### ISSUE THREAD

**Issue by willieconrad** [SAP/gigya-python-sdk#26]
I noticed that the host `accounts.us1.gigya.com`, perhaps along with others, is slowly migrating from Akamai to CloudFront, or at least appears to be.  Most of the time, I get a DNS record like this ...

```
nslookup accounts.us1.gigya.com

Non-authoritative answer:
accounts.us1.gigya.com	canonical name = socialize.gigya.com.edgekey.net.
socialize.gigya.com.edgekey.net	canonical name = e6600.b.akamaiedge.net.
Name:	e6600.b.akamaiedge.net
Address: 104.77.241.34
```

However, over the last week or so, I have been occasionally something more like this ...

```
Non-authoritative answer:
accounts.us1.gigya.com	canonical name = d2ps1zlxa98yt2.cloudfront.net.
Name:	d2ps1zlxa98yt2.cloudfront.net
Address: 18.239.168.36
Name:	d2ps1zlxa98yt2.cloudfront.net
Address: 18.239.168.34
Name:	d2ps1zlxa98yt2.cloudfront.net
Address: 18.239.168.42
Name:	d2ps1zlxa98yt2.cloudfront.net
Address: 18.239.168.24
```

Which is what leads me to believe this migration is occurring.  

This is an issue when using version 3.4.0 of the Python Gigya SDK, because it does not support SNI.  SNI is required by CloudFront (or at least the Gigya distributions are configured to require it), but not by Akamai.  Specifically the problem is the use of the deprecated module-level `ssl.wrap_socket` function in `ValidHTTPSConnection`:

```
    def connect(self):
        sock = socket.create_connection((self.host, self.port), self.timeout, self.source_address)

        if self._tunnel_host:
            self.sock = sock
            self._tunnel()
        ssl_context = SSLContext()
        self.sock = ssl.wrap_socket(sock, ca_certs=GSRequest.caCertsPath, cert_reqs=ssl.CERT_REQUIRED, server_hostname=self.host)
```

I think that this deprecated version does not honor the systems SNI settings.  If I modify my `/etc/hosts` to point to one of the CloudFront IP addresses, I get the following error when running the following code ...

```
>>> req = GSRequest(apiKey='trash', apiMethod='accounts.login')
>>> req.setAPIDomain('us1.gigya.com')
>>> req.send().getResponseText()
'{errorCode:500000,errorMessage:"<urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)>"}'
```

If I upgrade `connect` to look more like this, and use the newer context-specific version of `wrap_socket`, it works (it complains about the bad key of course, but it is making a valid HTTPS connection where it wasn't before) ...

```
def connect(self):
        sock = socket.create_connection((self.host, self.port), self.timeout, self.source_address)

        if self._tunnel_host:
            self.sock = sock
            self._tunnel()
        ssl_context = ssl.create_default_context(cafile=GSRequest.caCertsPath)
        self.sock = ssl_context.wrap_socket(sock, server_hostname=self.host)
```

```
>>> req = GSRequest(apiKey='trash', apiMethod='accounts.login')
>>> req.setAPIDomain('us1.gigya.com')
>>> req.send().getResponseText()
b'{\r\n  "callId": "01819c1e6d954a34b37ca8329ec01e0d",\r\n  "errorCode": 400093,\r\n  "errorDetails": "Missing required parameter: ApiKey",\r\n  "errorMessage": "Invalid ApiKey parameter",\r\n  "apiVersion": 2,\r\n  "statusCode": 400,\r\n  "statusReason": "Bad Request",\r\n  "time": "2024-05-20T16:53:19.620Z"\r\n}'
```

I was able to reproduce this consistently in GSSDK 3.4.0 with Python 3.8, 3.9, and 3.11.

I also noticed that `urllib.install_opener` is being used to install openers globally, and then re-installing the previous opener when complete, but I think it would be better to use the opener directly with `opener = build_opener()` and then `opener.open()`.

**Comment by kobico** [comment]
This issue was fixed in version 3.5.0
Thanks for submitting
